version: '3.8'

services:
  flask_api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    container_name: flask_api
    restart: always
    ports:
      - "5000:5000"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - WORKER_HOST=${WORKER_HOST}
      - WORKER_PORT=${WORKER_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - CHROMA_PATH=/app/chroma_db
    volumes:
      - ./api:/app
      - chroma_data:/app/chroma_db

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  chroma_data: