version: '3.8'

services:
  flask_frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: flask_frontend
    restart: always
    ports:
      - "80:80"
    environment:
      - API_URL=http://${API_HOST}:5000
    volumes:
      - ./frontend:/app