services:
  flask_app:
    build: .
    container_name: flask_app
    restart: always
    ports:
      - "5000:5000"
    environment:
      - CHROMA_PATH=/app/chroma_db
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
    volumes:
      - .:/app
      - chroma_data:/app/chroma_db
      - instance_data:/app/instance
    command: >
      sh -c "python app.py"

volumes:
  chroma_data:
  instance_data:
